[project]
name = "omninpc_backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.10.1",
    "elevenlabs>=2.30.0",
    "fastapi[standard]>=0.128.0",
    "langchain-openai>=1.1.7",
    "langgraph>=1.0.5",
    "numpy>=2.4.2",
    "pillow>=12.1.0",
]
