/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 67c80979f92092108aed4ca0.glb -o ./Your-Avatar.jsx -k -r public
*/

import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { useAnimations, useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useControls } from 'leva';
import { useChat } from '../context/useChat';

const AVATAR_MODEL_PATH = '/models/69522429df527aeb847ed70b.glb';
// const AVATAR_MODEL_PATH = '/models/67c80979f92092108aed4ca0.glb';

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    browInnerUp: 0.16999999999999982,
    eyeSquintLeft: 0.3999999999999997,
    eyeSquintRight: 0.43999999999999967,
    noseSneerLeft: 0.1700000727403591,
    noseSneerRight: 0.14000002836874018,
    mouthPressLeft: 0.6099999999999992,
    mouthPressRight: 0.4099999999999997,
  },
  sad: {
    eyeSquintLeft: 0.51,
    eyeSquintRight: 0.53,
    mouthFrownLeft: 0.52,
    mouthFrownRight: 0.51,
    eyeLookDownLeft: 0.51,
    eyeLookDownRight: 0.54,
    jawOpen: 0.15,
    mouthClose: 0.04,
  },
  surprised: {
    eyeWideLeft: 0.35000000000000003,
    eyeWideRight: 0.35000000000000003,
    jawOpen: 0.24,
    mouthRollLower: 1,
  },
  angry: {
    viseme_PP: 0.76,
    browDownLeft: 0.72,
    browDownRight: 0.81,
    browInnerUp: 0.37999999999964895,
    browOuterUpLeft: 0.19999999999981527,
    mouthShrugLower: 0.11999999999988908,
    mouthLeft: 0.53,
    cheekPuff: 0.91,
    mouthDimpleLeft: 0.48,
  },
  crazy: {
    viseme_FF: 0.13,
    browInnerUp: 0.62,
    eyeSquintLeft: 0.51,
    jawForward: 0.05814973697313278,
    noseSneerLeft: 0.03314535007468572,
    noseSneerRight: 0.029656365856297752,
    eyeLookDownLeft: 0.022931794353322765,
    eyeLookUpRight: 0.023491106410720868,
    eyeLookInLeft: 0.055931205739811564,
    eyeLookInRight: 0.055931205739811564,
    jawOpen: 0.366,
    mouthClose: 0.04,
    mouthDimpleRight: 0.055931205739811564,
    mouthStretchLeft: 0.016220049664545363,
    mouthStretchRight: 0.016779361721943466,
    mouthSmileLeft: 0.03244009932909073,
    mouthSmileRight: 0.022372482295924652,
  },
};

const corresponding = {
  A: 'viseme_PP',
  B: 'viseme_kk',
  C: 'viseme_I',
  D: 'viseme_AA',
  E: 'viseme_O',
  F: 'viseme_U',
  G: 'viseme_FF',
  H: 'viseme_TH',
  X: 'viseme_PP',
};

let setupMode = false;

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF(AVATAR_MODEL_PATH);

  // 這種寫法的性能可能會好一些，但是脣形會動不起來，所以先沿用上方的舊寫法
  // import { useGraph } from '@react-three/fiber';
  // import { useGLTF } from '@react-three/drei';
  // import { SkeletonUtils } from 'three-stdlib';
  // const { scene } = useGLTF(AVATAR_MODEL_PATH);
  // const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // const { nodes, materials } = useGraph(clone);

  const DEFAULT_ANIMATION = 'Idle';

  const { animations } = useGLTF('/models/animations.glb');
  const { currentMessage, onMessagePlayed, audioRef, resetAudio } = useChat();
  const [facialExpression, setFacialExpression] = useState('');
  const [lipsync, setLipsync] = useState();
  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [animation, setAnimation] = useState(
    // Check if Idle animation exists otherwise use first animation
    animations.find((a) => a.name === DEFAULT_ANIMATION)
      ? DEFAULT_ANIMATION
      : animations[0].name
  );
  const group = useRef();
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    try {
      if (!currentMessage) {
        setAnimation(DEFAULT_ANIMATION);
        return;
      }
      setAnimation(currentMessage.animation);
      setFacialExpression(currentMessage.facialExpression);
      setLipsync(currentMessage.lipsync);

      resetAudio();

      const audio = audioRef.current;

      // 如果有 audioUrl，表示是預設的回應，而非動態產出
      if (currentMessage.audioUrl) {
        audio.src = currentMessage.audioUrl;
      } else {
        audio.src = `data:audio/wav;base64,${currentMessage.audio}`;
      }

      audio.onended = () => {
        if (typeof onMessagePlayed === 'function') {
          onMessagePlayed();
        }
      };

      // 先掛載事件再 play
      audio.play().catch((error) => {
        console.error(error);
        onMessagePlayed();
      });
    } catch (error) {
      console.error(error);
      onMessagePlayed();
    }
  }, [currentMessage]);

  useEffect(() => {
    actions[animation]
      .reset()
      .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
      .play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation]);

  function lerpMorphTarget(target, value, speed = 0.1) {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }

        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {
            console.error(e);
          }
        }
      }
    });
  }

  const defaultMorphSwitchState = {
    value: null,
    lastSwitch: 0,
    delay: 0,
  };
  const fallbackMouthCues = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']; // 自訂想用來替代的嘴型
  const fallbackMouthRef = useRef({ ...defaultMorphSwitchState });

  let last = 0;
  useFrame((state) => {
    let intervalTime = 1;
    // 模型在講話的時候，re-render 的速度快一點
    if (!audioRef.current.paused && !audioRef.current.ended) {
      intervalTime = 0.033;
    }
    if (state.clock.elapsedTime - last <= intervalTime) {
      return;
    }
    last = state.clock.elapsedTime;

    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === 'eyeBlinkLeft' || key === 'eyeBlinkRight') {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget('eyeBlinkLeft', blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget('eyeBlinkRight', blink || winkRight ? 1 : 0, 0.5);

    // LIPSYNC
    if (setupMode) {
      return;
    }

    const appliedMorphTargets = [];
    if (currentMessage && lipsync) {
      // 透過將時間取模，讓嘴型動畫可無限循環播放
      const currentAudioTime =
        audioRef.current?.currentTime % lipsync.metadata.duration;
      const mouthCue = lipsync.mouthCues.find(
        (mc) => currentAudioTime >= mc.start && currentAudioTime <= mc.end
      );
      const needFallback = mouthCue?.value === 'X';

      if (mouthCue) {
        if (needFallback) {
          // 嘴型為 X (閉合嘴型)，使用 fallback 嘴型
          const now = performance.now();
          const ref = fallbackMouthRef.current;

          if (!ref.value || now - ref.lastSwitch > ref.delay) {
            ref.value =
              fallbackMouthCues[
                Math.floor(Math.random() * fallbackMouthCues.length)
              ];
            ref.lastSwitch = now;
            ref.delay = 100 + Math.random() * 100;
          }

          const fallback = ref.value;
          appliedMorphTargets.push(corresponding[fallback]);
          lerpMorphTarget(corresponding[fallback], 1, 0.2);
        } else {
          // 非閉合嘴型
          fallbackMouthRef.current = { ...defaultMorphSwitchState };
          appliedMorphTargets.push(corresponding[mouthCue.value]);
          lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2);
        }
      } else {
        fallbackMouthRef.current = { ...defaultMorphSwitchState };
      }
    }

    Object.values(corresponding).forEach((value) => {
      if (appliedMorphTargets.includes(value)) {
        return;
      }
      lerpMorphTarget(value, 0, 0.1);
    });
  });

  /* useControls('FacialExpressions', {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === 'eyeBlinkLeft' || key === 'eyeBlinkRight') {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  }); */

  const [, set] = useControls('MorphTarget', () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(
        () => {
          setBlink(true);
          setTimeout(() => {
            setBlink(false);
            nextBlink();
          }, 200);
        },
        THREE.MathUtils.randInt(2000, 5000)
      );
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  // console.warn(nodes);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Hair"
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      {/* <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      /> */}
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload(AVATAR_MODEL_PATH);
useGLTF.preload('/models/animations.glb');

// ?morphTargets=mouthSmile,ARKit
